# Generated by Django 4.2.3 on 2023-10-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_feedback'),
        ('taxi', '0002_user'),
    ]

    operations = [
    ]
